--CREATE TABLE (auto commiting)


--CREATIN BASIC TABLE

CREATE TABLE LOCATIONS (
LOCATION_ID NUMBER PRIMARY KEY,
LOCATION_CITY VARCHAR2(100),
LOCATION_COUNTRY VARCHAR2(100)
)

CREATE TABLE EMPLOYEES (
EMPLOYEE_ID NUMBER PRIMARY KEY, 
EMPLOYEE_NAME VARCHAR2(100),
EMPLOYEE_SALARY NUMBER,
EMPLOYEE_MANAGER_ID NUMBER
);


CREATE TABLE SCHOOLS (
SCHOOL_ID NUMBER PRIMARY KEY,
SCHOOL_NAME VARCHAR2(200) UNIQUE,
LOCATION_ID NUMBER NOT NULL,
SCHOOL_PHONE_NUMBER NUMBER NOT NULL,
SCHOOL_EMAIL VARCHAR2(200) NOT NULL,
CONSTRAINT SCHOOL_LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);


CREATE TABLE STUDENTS (
STUDENT_NATIONAL_ID NUMBER PRIMARY KEY,
STUDENT_NAME VARCHAR2(200),
SCHOOL_ID NUMBER,
STUDENT_AGE NUMBER NOT NULL,
STUDENT_GRADE VARCHAR2(200),
STUDENT_GENDER_ VARCHAR2(1),
STUDENT_DATE_OF_BIRTH DATE,
PARENTS_PHONE_NUMBER NUMBER,
JOINED_SCHOOL_DATE DATE,
CONSTRAINT STUDENT_SCHOOL_FK FOREIGN KEY (SCHOOL_ID) REFERENCES   SCHOOLS(SCHOOL_ID)
)


CREATE TABLE TEACHERS (
TEACHER_ID NUMBER PRIMARY KEY ,
TEACHER_NAME VARCHAR2(100),
SCHOOL_ID NUMBER,
SALARY NUMBER,
TEACHER_GENDER VARCHAR2(1),
TEACHER_PHONE_NUMBER NUMBER,
DATE_OF_JOIN DATE,
CONSTRAINT TEACHER_SCHOOL_FK FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOLS(SCHOOL_ID)
)


CREATE TABLE CLASSES (
CLASS_NUMBER NUMBER PRIMARY KEY,
CLASS_TEACHER NUMBER,
CLASS_SCHOOL NUMBER,
CONSTRAINT CLASS_TEACHER_FK FOREIGN KEY (CLASS_TEACHER) REFERENCES TEACHERS(TEACHER_ID),
CONSTRAINT CLASS_SCHOOL_FK FOREIGN KEY (CLASS_SCHOOL) REFERENCES SCHOOLS(SCHOOL_ID)
)

CREATE TABLE SUBJECTS (
SUBJECT_ID NUMBER PRIMARY KEY,
SUBJECT_NAME VARCHAR2(50)
);

--boolean value
create table active(
is_active boolean primary key
);


--CREATING A TABLE AS A COPY OF A WHOLE ANOTHER TABLE 
CREATE TABLE PLAYERS_COPY AS  
SELECT * FROM PLAYERS;

--CREATING A TABLE AS A COPY OF A COLUMN(S) IN ANOTHER TABLE 
CREATE TABLE PLAYERS_COPY_NAMES AS  
SELECT PLAYER_NAME FROM PLAYERS;

CREATE TABLE PLAYERS_COPY_NAMES_AND_SALARIES AS  
SELECT PLAYER_NAME,PLAYER_SALARY FROM PLAYERS;


--SETTING DEFAULT VALUE(ANYTIME A ROW IS INSERTED THIS COLUMN WILL TAKE THE DEFAULT VALUE IS NULL)
CREATE TABLE INVOICES (
INVOICE_ID NUMBER,
INVOICE_DATE DATE DEFAULT SYSDATE
);

--MULTIPLE PRIMARY KEYS
CREATE TABLE SALES (
SALES_DAY DATE,
SALES_ID NUMBER,
SALES_AMOUNT NUMBER ,
CONSTRAINT SALES_PK PRIMARY KEY (SALES_DAY,SALES_ID)
);

--OTHER CONSTRAINTS (NOT NULL, UNIQUE, CHECK)
CREATE TABLE KINDER_GARTEN(
JUNIOR_NAME VARCHAR2(100) NOT NULL ,
JUNIOR_AGE NUMBER CHECK (JUNIOR_AGE < 5),
JUNIOR_ID NUMBER UNIQUE
);


--ENABLING/DISABLING CONSTRAINTS
ALTER TABLE KINDER_GARTEN DISABLE CONSTRAINT SYS_C008601;
ALTER TABLE KINDER_GARTEN ENABLE CONSTRAINT SYS_C008601;


--ALTER ADDING COLUMN
ALTER TABLE TEACHERS 
ADD SUBJECT NUMBER

ALTER TABLE CLASSES 
ADD CLASS_ID NUMBER;


ALTER TABLE KINDER_GARTEN 
ADD FAV_FOOD VARCHAR2(100);



--ALTER DROP COLUMN
ALTER TABLE KINDER_GARTEN DROP COLUMN FAV_FOOD;


--ALTER ADDING CONSTRAINT
ALTER TABLE TEACHERS 
ADD CONSTRAINT TEACHER_SUBJECT_FK 
FOREIGN KEY (SUBJECT)
REFERENCES SUBJECTS(SUBJECT_ID)


ALTER TABLE CLASSES 
ADD CONSTRAINT CLASS_PK
PRIMARY KEY (CLASS_ID)

ALTER TABLE STUDENTS 
ADD CONSTRAINT STUDENT_CLASS_FK
FOREIGN KEY (STUDENT_CLASS)
REFERENCES CLASSES(CLASS_ID)

--ALTER EDITING COLUMNS DATA TYPES
ALTER TABLE CLASSES 
MODIFY CLASS_NUMBER VARCHAR2(50)


ALTER TABLE STUDENTS 
MODIFY STUDENT_CLASS NUMBER



--REMOVING A CONSTRAINT
ALTER TABLE CLASSES 
DROP CONSTRAINT CLASS_PK ;


ALTER TABLE SCHOOLS 
DROP CONSTRAINT SYS_C008580;

--CHANING COLUMN NAME 
ALTER TABLE STUDENTS 
RENAME COLUMN STUDENT_GRADE TO STUDENT_CLASS;


ALTER TABLE EMPLOYEES 
RENAME COLUMN EMPLOYEE_MANAGER_ID TO PLAYER_IDOL_ID;


--CHANING TABLE NAME 
ALTER TABLE EMPLOYEES 
RENAME TO PLAYERS;


--DESCRIBING A TABLE 
DESC SCHOOLS;