--CREATE TABLE (auto commiting)


--CREATIN BASIC TABLE

CREATE TABLE LOCATIONS (
LOCATION_ID NUMBER PRIMARY KEY,
LOCATION_CITY VARCHAR2(100),
LOCATION_COUNTRY VARCHAR2(100)
)


-- CREATIN TABLE WITH FOREIGN KEY

CREATE TABLE SCHOOLS (
SCHOOL_ID NUMBER PRIMARY KEY,
SCHOOL_NAME VARCHAR2(200) UNIQUE,
LOCATION_ID NUMBER NOT NULL,
SCHOOL_PHONE_NUMBER NUMBER NOT NULL,
SCHOOL_EMAIL VARCHAR2(200) NOT NULL,
CONSTRAINT SCHOOL_LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);


CREATE TABLE STUDENTS (
STUDENT_NATIONAL_ID NUMBER PRIMARY KEY,
STUDENT_NAME VARCHAR2(200),
SCHOOL_ID NUMBER,
STUDENT_AGE NUMBER NOT NULL,
STUDENT_GRADE VARCHAR2(200),
STUDENT_GENDER_ VARCHAR2(1),
STUDENT_DATE_OF_BIRTH DATE,
PARENTS_PHONE_NUMBER NUMBER,
JOINED_SCHOOL_DATE DATE,
CONSTRAINT STUDENT_SCHOOL_FK FOREIGN KEY (SCHOOL_ID) REFERENCES   SCHOOLS(SCHOOL_ID)
)


CREATE TABLE TEACHERS (
TEACHER_ID NUMBER PRIMARY KEY ,
TEACHER_NAME VARCHAR2(100),
SCHOOL_ID NUMBER,
SALARY NUMBER,
TEACHER_GENDER VARCHAR2(1),
TEACHER_PHONE_NUMBER NUMBER,
DATE_OF_JOIN DATE,
CONSTRAINT TEACHER_SCHOOL_FK FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOLS(SCHOOL_ID)
)


CREATE TABLE CLASSES (
CLASS_NUMBER NUMBER PRIMARY KEY,
CLASS_TEACHER NUMBER,
CLASS_SCHOOL NUMBER,
CONSTRAINT CLASS_TEACHER_FK FOREIGN KEY (CLASS_TEACHER) REFERENCES TEACHERS(TEACHER_ID),
CONSTRAINT CLASS_SCHOOL_FK FOREIGN KEY (CLASS_SCHOOL) REFERENCES SCHOOLS(SCHOOL_ID)
)

CREATE TABLE SUBJECTS (
SUBJECT_ID NUMBER PRIMARY KEY,
SUBJECT_NAME VARCHAR2(50)
)


--ALTER ADDING COLUMN
ALTER TABLE TEACHERS 
ADD SUBJECT NUMBER

ALTER TABLE CLASSES 
ADD CLASS_ID NUMBER

--ALTER ADDING CONSTRAINT
ALTER TABLE TEACHERS 
ADD CONSTRAINT TEACHER_SUBJECT_FK 
FOREIGN KEY (SUBJECT)
REFERENCES SUBJECTS(SUBJECT_ID)


ALTER TABLE CLASSES 
ADD CONSTRAINT CLASS_PK
PRIMARY KEY (CLASS_ID)

ALTER TABLE STUDENTS 
ADD CONSTRAINT STUDENT_CLASS_FK
FOREIGN KEY (STUDENT_CLASS)
REFERENCES CLASSES(CLASS_ID)

SELECT * FROM CLASSES
--ALTER EDITING COLUMNS DATA TYPES

ALTER TABLE CLASSES 
MODIFY CLASS_NUMBER VARCHAR2(50)


ALTER TABLE STUDENTS 
MODIFY STUDENT_CLASS NUMBER



--REMOVING A PRIMARY KEY
ALTER TABLE CLASSES 
DROP CONSTRAINT CLASS_PK 

--CHANING COLUMN NAME 
ALTER TABLE STUDENTS 
RENAME COLUMN STUDENT_GRADE TO STUDENT_CLASS

