--SELECTING

--BASIC SELECTING 
SELECT * FROM STUDENTS;
SELECT * FROM CLASSES;
SELECT * FROM SCHOOLS;
SELECT * FROM LOCATIONS;
SELECT * FROM STUDENTS;
SELECT * FROM SUBJECTS;
SELECT * FROM TEACHERS;
SELECT * FROM employees;


--SELECTING CERTAIN COLUMNS IN A TABLE
SELECT TEACHER_NAME FROM TEACHERS;
SELECT TEACHER_ID,TEACHER_NAME,TEACHER_PHONE_NUMBER,DATE_OF_JOIN FROM TEACHERS;

--SELECTING WITH CONDITION(S)
SELECT * FROM TEACHERS 
WHERE SCHOOL_ID = 20;

SELECT * FROM TEACHERS 
WHERE SCHOOL_ID = 20 AND SUBJECT = 12;

--JOINS (SELECTING FROM MULTIPLE TABLES)
--inner join (where should be common column between tables)
--OLD SYNTAX
SELECT C.CLASS_NUMBER,T.TEACHER_NAME
FROM CLASSES C, TEACHERS T
WHERE C.CLASS_TEACHER = T.TEACHER_ID;

SELECT C.CLASS_NUMBER,T.TEACHER_NAME,SUB.SUBJECT_NAME,S.SCHOOL_NAME,L.LOCATION_CITY,L.LOCATION_COUNTRY
FROM CLASSES C,TEACHERS T,SCHOOLS S, LOCATIONS L,SUBJECTS SUB
WHERE C.CLASS_SCHOOL = S.SCHOOL_ID AND S.LOCATION_ID = L.LOCATION_ID AND C.CLASS_TEACHER = T.TEACHER_ID AND T.SUBJECT = SUB.SUBJECT_ID
ORDER BY CLASS_NUMBER;


--NEW SYNTAX
SELECT C.CLASS_NUMBER,T.TEACHER_NAME
FROM CLASSES C
JOIN TEACHERS T
ON C.CLASS_TEACHER = T.TEACHER_ID;

--EQUIVELANT BUT BOTH THE REFERENCED COLUMN MUST EXIST WITH THE SAME NAME IN BOTH TABLES
SELECT S.SCHOOL_NAME,L.LOCATION_CITY
FROM SCHOOLS S
JOIN LOCATIONS L
USING (LOCATION_ID);


SELECT C.CLASS_NUMBER,T.TEACHER_NAME,SUB.SUBJECT_NAME,S.SCHOOL_NAME,L.LOCATION_CITY,L.LOCATION_COUNTRY
FROM CLASSES C
INNER JOIN SCHOOLS S ON C.CLASS_SCHOOL = S.SCHOOL_ID
INNER JOIN LOCATIONS L ON S.LOCATION_ID = L.LOCATION_ID
INNER JOIN TEACHERS T ON C.CLASS_TEACHER = T.TEACHER_ID
INNER JOIN SUBJECTS SUB ON T.SUBJECT = SUB.SUBJECT_ID
ORDER BY CLASS_NUMBER;

--left join (displaying all rows of left table and if no similar rows in the right table display null)
--NEW SYNTAX
select T.teacher_name,C.class_number
from TEACHERS T
LEFT JOIN CLASSES C 
ON C.CLASS_TEACHER = T.TEACHER_ID;


--OLD SYNTAX
SELECT T.TEACHER_NAME,C.CLASS_NUMBER
FROM TEACHERS T, CLASSES C
WHERE T.TEACHER_ID = C.CLASS_TEACHER(+);

--RIGHT join (displaying all rows of RIGHT table and if no similar rows in the right table display null)
--NEW SYNTAX
select T.teacher_name,C.class_number
from  CLASSES C
RIGHT JOIN  TEACHERS T
ON C.CLASS_TEACHER = T.TEACHER_ID;


--OLD SYNTAX
SELECT T.TEACHER_NAME,C.CLASS_NUMBER
FROM TEACHERS T, CLASSES C
WHERE  C.CLASS_TEACHER(+) = T.TEACHER_ID;


--OUTER JOIN (SELECTING ALL ROWS FROM BOTH TABLES)
--NEW SYNTAX ("FULL OUTER JOIN")
SELECT T.TEACHER_NAME,S.SUBJECT_NAME
FROM TEACHERS T 
FULL OUTER JOIN SUBJECTS S
ON T.SUBJECT = S.SUBJECT_ID
ORDER BY TEACHER_NAME;

--OLD SYNTAX (LEFT JOIN UNION RIGHT JOIN)
SELECT T.TEACHER_NAME,S.SUBJECT_NAME
FROM TEACHERS T, SUBJECTS S
WHERE S.SUBJECT_ID(+) = T.SUBJECT
UNION
SELECT T.TEACHER_NAME,S.SUBJECT_NAME
FROM TEACHERS T, SUBJECTS S
WHERE S.SUBJECT_ID = T.SUBJECT(+)
ORDER BY TEACHER_NAME;


--CROSS JOIN
--NEW SYNTAX
SELECT  C.CLASS_NUMBER || ' ' || S.SCHOOL_NAME AS "CLASSES"
FROM CLASSES C
CROSS JOIN SCHOOLS S;

--OLD SYNTAX
SELECT C.CLASS_NUMBER || ' ' || S.SCHOOL_NAME AS "CLASSES" 
FROM CLASSES C, SCHOOLS S;


--self join 
--NEW SYNTAX
select PL2.PLAYER_NAME,PL1.PLAYER_NAME AS "Idol Name"
from PLAYERS PL1
RIGHT JOIN  PLAYERS PL2 
ON PL1.PLAYER_ID = PL2.PLAYER_IDOL_ID ;


--OLD SYNTAX
SELECT PL1.PLAYER_NAME,PL2.PLAYER_NAME AS "IDOL NAME"
FROM PLAYERS PL1 , PLAYERS PL2 
WHERE PL1.PLAYER_IDOL_ID = PL2.PLAYER_ID(+);

--NATURALJOIN (SELECTING ONLY ROWS THAT HAS COMMON COLOUMN)
--NEW SYNTAX
SELECT * FROM SCHOOLS S, LOCATIONS L WHERE S.LOCATION_ID = L.LOCATION_ID ORDER BY L.LOCATION_ID;

--OLD SYNTAX
SELECT * FROM SCHOOLS NATURAL JOIN LOCATIONS ORDER BY LOCATION_ID;


