--ABS
SELECT ABS(-100) FROM DUAL; 
--OUTPUT 100

--CEIL
SELECT CEIL(1.1) FROM DUAL;
--OUTPUT 2 , ROUND UP TO NEXT INTEGER

--FLOOR
SELECT FLOOR(1.1) FROM DUAL;
--OUTPUT 1 , ROUND UP TO PREV INTEGER

--ROUND 
SELECT ROUND(1.3562,2) FROM DUAL;
--OUTPUT 1.36 ROUND N'TH DECIMAL

--TRUNC
SELECT TRUNC(1.3562,2) FROM DUAL;
--OUTPUT 1.35 CUTTS OF DECIMALS WITHOUT ROUNDING

--MOD
SELECT MOD(100,44) FROM DUAL; 
--OUTPUT 12 , REMAINING AFTER DEVISION , 10/4 => 2.5 TAKE THE 2 , 2 * 44 => 88 ,TAKE THE 88 , 100 - 88 => (12)


--POWER
SELECT POWER(3,3) FROM DUAL;
--OUTPUT 27, 3 * 3 * 3 


--SQRT
SELECT SQRT(25) FROM DUAL;
--OUTPUT 5 , SQUARE ROOT


--UPPER 
SELECT UPPER('abdallah') from dual;
--OUT PUT 'ABDALLAH',CONVERT ALL TO UPPER CASE


--LOWER 
SELECT LOWER('ABDALLAH') from dual;
--OUT PUT 'abdallah',CONVERT ALL TO LOWER CASE


--INITCAP 
SELECT INITCAP('abdallah mohamed') from dual;
--OUT PUT 'Abdallah Mohamed',CONVERT first letter to upper CASE


--length
select length('abdallah') from dual;
--output 8, count of character


--SUBSTR
SELECT SUBSTR('ABDALLAH' , 2, 4) FROM DUAL;
--OUTPUT 'BDAL' , STARTS FROM 2ND CHARACTER, GO 4 CHARACTERS

--INSTR
SELECT INSTR('ABDA-LLAH', 'A') FROM DUAL;
--OUTPUT 1 , POSITION OF FIRST A


--CONCAT
SELECT CONCAT('ABDALLAH','MOHAMED') FROM DUAL;
--OUTPUT ABDALLAHMOHAMED , JOINS STRINGS


SELECT 'ABDALLAH' || ' MOHAMED' FROM DUAL;
--OUTPUT ABDALLAH MOHAMED , JOINS STRINGS


--LPAD
SELECT LPAD('ABDALLAH',10,'+') FROM DUAL;
--OUTPUT '++ABDALLAH' , TEXT LENGHT IS 8, 10-8 = 2 , ADDS 2 OF THE '+' ON THE LEFT 

--RPAD
SELECT RPAD('ABDALLAH',10,'+') FROM DUAL;
--OUTPUT '++ABDALLAH' , TEXT LENGHT IS 8, 10-8 = 2 , ADDS 2 OF THE '+' ON THE RIGHT 


--TRIM 
SELECT TRIM(LEADING '+' FROM '++++++ABDALLAH+++++++') FROM DUAL;
--OUTPUT 'ABDALLAH+++++++' , REMOVES SELECTED STRING FROM THE START 


--TRIM 
SELECT TRIM(TRAILING '+' FROM '++++++ABDALLAH+++++++') FROM DUAL;
--OUTPUT '+++++++ABDALLAH' , REMOVES SELECTED STRING FROM THE END 


--TRANSLATE
SELECT TRANSLATE('123','13','AC') FROM DUAL;
--output 'A2C' , REPLACING EVERY CHARCTER WITH ITS CORRISPONDIING


--SYSDATE
SELECT SYSDATE FROM DUAL;
--CURRENT DATE/TIME


--CURRENT_DATE
SELECT CURRENT_DATE FROM DUAL;
--SESSION'S DATE N TIME


--ADD_MONTHS
SELECT ADD_MONTHS(SYSDATE,17) FROM DUAL;
--ADDS 17 MONTHS FROM CURRENT DATE 


--MONTHS_BETWEEN 
SELECT MONTHS_BETWEEN(TO_DATE('2026-3-5','YYYY-MM-DD'),SYSDATE) FROM DUAL;
--OUTPUT (MONTHS BETWEEN TWO DATES, COULD BE IN NEGATIVE IF STATING DATE IS OLDER)


--MAX
SELECT MAX(SALARY) FROM HR.EMPLOYEES;
-- MAXIMUM VALUE 

--MIN
SELECT MIN(SALARY) FROM HR.EMPLOYEES;
-- MINIMUM VALUE 


--SUM
SELECT SUM(SALARY) FROM HR.EMPLOYEES;
-- SUM VALUE 


--AVG
SELECT AVG(SALARY) FROM HR.EMPLOYEES;
-- AVERAGE VALUE 


--LISTAGG
SELECT DEPARTMENT_ID,LISTAGG(LAST_NAME,', ') ALL_NAMES FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;
--CONCAT MULTIPLE ROWS VALUES IN ONE ROW WITH A SEPERATOR




